In [2]:
import pandas as pd
import pyodbc
server = 'DESKTOP-OLVG7PI'
database = 'newdata'
username = 'sa'
password = 'Kasmo@123'
driver = '{ODBC Driver 17 for SQL Server}'

In [3]:
connection_string=f"DRIVER={driver};SERVER={server};DATABASE={database};UID={username};PWD={password}"
conn=pyodbc.connect(connection_string)
cursor=conn.cursor()

In [4]:
from sqlalchemy import create_engine
engine = create_engine(
    "mssql+pyodbc://sa:Kasmo%40123@DESKTOP-OLVG7PI/newdata?driver=ODBC+Driver+17+for+SQL+Server",
    fast_executemany=True)

In [5]:
df_cus = pd.read_csv(r"C:\Users\Saikiran\Downloads\order_data 1.csv")

In [6]:
df_orders = pd.read_csv(r"C:\Users\Saikiran\Downloads\cus_data.csv")

In [7]:
df_cus.to_sql('only_customer', con=engine, if_exists='replace', index=False)

-1

In [8]:
df_orders.to_sql('orders', con=engine, if_exists='replace', index=False)

-1

In [11]:
customers_df = pd.read_sql("SELECT * FROM only_customer", con=engine)
orders_df = pd.read_sql("SELECT * FROM orders", con=engine)

unified_df = pd.merge(customers_df, orders_df, how='inner', on='customer_id')

In [12]:
unified_df

,order_id,customer_id,order_date,order_amount,order_status,product_category,Unnamed: 0,name,email,phone,address,registration_date,loyalty_status
0,892a07a4-d252-4775-85e0-73077143e1c6,966,2024-11-27,317.64,Cancelled,Home & Garden,965,Felicia Tate,robertskimberly@example.org,+91 6402548903,"22253 Carolyn Curve Apt. 653, West Rebecca, PA...",2024-01-29,Bronze
1,ae160758-e187-47b2-9350-032f88f55491,345,2023-03-27,645.87,Completed,Home & Garden,344,Amy Brewer,fmccormick@example.net,+91 8359312927,"8819 Joseph Coves Suite 078, New Samanthamouth...",2023-07-20,Gold
2,7c50456e-6123-45cc-aa19-128bef3754d6,503,2024-03-31,880.86,Pending,Clothing,502,Charles Leonard,gwest@example.net,+91 2239783174,"3114 James Ridge, Marcustown, FL 75556",2025-03-04,Bronze
3,c788b56b-3716-4cd9-a827-d4dc401ba00c,385,2023-08-09,876.83,Cancelled,Home & Garden,384,Katherine Brown,taylorcharles@example.com,+91 8983525442,"987 Caitlin Club, Harrisville, WV 42076",2025-03-26,Silver
4,925ab5b1-adb1-4302-a70b-1c2db724e02b,817,2023-04-19,264.53,Pending,Home & Garden,816,Derrick Jackson,eringrant@example.net,+91 1434811147,"409 Best Locks, Watersborough, NE 67440",2023-08-15,Silver
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,cb6f0f6b-3d4b-402c-ba9e-a8e666422d97,799,2023-11-20,634.62,Cancelled,Clothing,798,Joan Peters,matthew92@example.com,+91 2704366110,"4563 William Avenue Apt. 687, Jamesmouth, RI 5...",2024-03-27,Bronze
1996,900fdea4-fd87-486d-bc20-26d045767ed8,692,2023-07-20,945.97,Cancelled,Electronics,691,Tony George,heathercarrillo@example.org,+91 3834198973,"762 Ian Forest Apt. 665, Joannaburgh, NJ 80663",2023-11-13,Silver
1997,4550ccfe-18c1-45d5-8c31-0edf1e3d9fa3,695,2024-01-06,229.99,Cancelled,Home & Garden,694,Zachary Jackson,zcox@example.org,+91 2885956521,"PSC 4908, Box 2340, APO AE 41815",2024-11-05,Bronze
1998,dd19b028-dfa2-4eda-a66f-44f5401ef27e,502,2023-02-05,596.65,Completed,Electronics,501,Robert Hicks,eharvey@example.com,+91 9667883510,"3612 Charles Walk, Port John, TX 17412",2024-08-19,Gold
1999,5e32ff66-d3dd-48ad-8e47-cd71bb2e97ea,348,2024-11-02,238.69,Completed,Books,347,Shawn Alvarez,bassjacob@example.net,+91 9974733273,"USCGC Long, FPO AP 89920",2023-08-26,Bronze